name: Deploy Vite App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # İhtiyacınıza göre Node.js sürümünü belirleyin

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          # Buraya deploy komutlarınızı ekleyin
          # Örneğin, bir FTP sunucusuna veya başka bir platforma dağıtım yapabilirsiniz
          echo "Deploying the app..."
